# Site settings
title: MBSN.COM
email: qy@shytime.com
description: > # this means to ignore newlines until "baseurl:"
 Most Beautiful Style NetWork.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://MBSN.com" # the base hostname & protocol for your site


# Sidebar filter
# Choose 'tag' or 'category' as filter in sidebar.
filter: 'tag'


# Social account
# twitter:  username
weibo:  SHYTIME
github:   SHYTIME
# codepen:  username
# dribbble: username


# Comment
# disqus_shortname: discussion_shortname


# Google Analytics
# google_analytics: tracking_ID


# Build settings
markdown: kramdown
sass:
  style: compressed
gems:
  - jekyll-sitemap
